name: Build

on:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: mickem/clean-after-action@v1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.x

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Setup VisualStudio 2022 Build Tools
        run: |
          choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.Universal"

      - name: Build Packages
        run: |
          dotnet restore .\ShadowPluginLoader.WinUI\ShadowPluginLoader.WinUI.csproj
          dotnet build -p:Configuration=Release .\ShadowPluginLoader.WinUI\ShadowPluginLoader.WinUI.csproj

 